site_name: Shoal

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - tables
  - admonition

nav:
  - Home: index.md
  - Initial Setup: first-setup.md
  - Deployment Guides:
    - Deploy an Application: deploy-app.md
    - Deploy with a Database: deploy-app-database.md
    - Deploy with a Scheduler: deploy-app-scheduler.md
    - Deploy with Multiple Containers: deploy-app-multi.md
  - FAQ & Guides:
    - Overview: faq.md
    - Zipping a Project Folder: guide-zip.md
    - Writing a Dockerfile: guide-dockerfile.md
    - What is eu1.shoal.live?: faq-shoal-live.md
    - Setting up a Custom Domain: faq-custom-domain.md
    - Environment Variables: faq-env-vars.md
    - Framework Default Ports: faq-port.md
    - Crontab Expressions: faq-crontab.md
    - Why is my Deployment Failing?: faq-deployment-failing.md
    - Deploying a Private GitHub Repo: faq-private-repo.md
